### ISSUE TITLE
Descriptions bug

### ISSUE THREAD

**Issue by JorgeLopez14** [imranbarbhuiya/pagination.djs#123]
### Issue description

When I want to make a pagination of descriptions, it does not create several descriptions, it creates all the data in a single one.

### Code sample

```TypeScript
const pagination = new Pagination(interaction);
      const descriptions = ["1", "2", "3", "4"];
pagination.setDescriptions(descriptions);
pagination.render();
```

### Package version

4.0.9

### Node.js version

18

**Comment by imranbarbhuiya** [comment]
I didn't really understand what u mean. Can u send some screenshots that can explain the issue?

**Comment by imranbarbhuiya** [comment]
Lmk if `limit` option help u to fix the issue
