### ISSUE TITLE
TypeError setEmoji when trying to remove buttons 

### ISSUE THREAD

**Issue by Spilyah** [imranbarbhuiya/pagination.djs#231]
### Issue description

Hi!

When I try to use `pagination.buttons = { prev: new ButtonBuilder(), next: new ButtonBuilder() };` to remove the "First" and "Last" buttons as mentioned in the documentation, I get the "TypeError: Cannot read properties of undefined (reading 'setEmoji')".

Everything is working fine without this pagination buttons line. 
I tried to reset the emoji with "pagination.setEmojis" but i get tge same error.

### Code sample

```TypeScript
const pagination = new Pagination(interaction);        
pagination.setEmbeds(gameEmbeds, (embed, index, array) => {
      return embed.setFooter({ text: `Jeu : ${index + 1}/${array.length}` });
});
pagination.setAuthorizedUsers([]); 
pagination.buttons = { prev: new ButtonBuilder(), next: new ButtonBuilder() };
pagination.render();
```

### Package version

4.0.12

### Node.js version

18.17.1

### Operating system

Windows

### I have tested this issue on a next release

0f86298

**Comment by imranbarbhuiya** [comment]
Hi, I was on vacation so I wasn't able to check the issue, I will fix it today

**Comment by imranbarbhuiya** [comment]
try using `4.0.13` and lmk if you are still having any issue
