### ISSUE TITLE
Add the ability to defer the reply first

### ISSUE THREAD

**Issue by newtykins** [imranbarbhuiya/pagination.djs#3]
At the moment, the library appears to only support .reply()-ing to the interaction. This pulls up an error when you first have to defer your reply, perhaps to fetch content that may take a while to return. I think it would be a good idea to add support for the people who have already replied to their interaction by deferring it.

**Comment by imranbarbhuiya** [comment]
> At the moment, the library appears to only support .reply()-ing to the interaction. This pulls up an error when you first have to defer your reply, perhaps to fetch content that may take a while to return. I think it would be a good idea to add support for the people who have already replied to their interaction by deferring it.

You can defer the reply before using Pagination and then use `.editReply()` instead of `.reply()` or `.render()`

**Comment by newtykins** [comment]
Oh, thank you! I just thought it would be more intuitive to have one method to respond to the interaction either way, as you can check if `interaction.deferred` is true, or something similar to that.

**Comment by imranbarbhuiya** [comment]
> Oh, thank you! I just thought it would be more intuitive to have one method to respond to the interaction either way, as you can check if `interaction.deferred` is true, or something similar to that.

Ty for the suggestion, I'll add check for `replied`, `deferred` and will use `editReply` instead of `reply()` in `render()` but `reply()` will always reply to the interaction.

**Comment by imranbarbhuiya** [comment]
fixed in v2.0.2
