### ISSUE TITLE
Found non-callable @@iterator Issue

### ISSUE THREAD

**Issue by DiamondMurder** [imranbarbhuiya/pagination.djs#33]
I have this issue when trying to use `.addActionsRows`

The error is: ```TypeError: Found non-callable @@iterator```

**Comment by imranbarbhuiya** [comment]
can you provide some reproducible code sample?

**Comment by imranbarbhuiya** [comment]
Since You haven't provided any code sample, I'm assuming you fixed it and closed the issue. If you haven't, without any code sample I'm guessing you are `MessageActionRow` directly to `addActionsRows` instead of an array of `MessageActionRow`.

```diff
- .addActionsRows(yourActionRow);
+ .addActionsRows([yourActionRow]);
```
