### ISSUE TITLE
Upgrade to support discord v14

### ISSUE THREAD

**Issue by ThatGuyJamal** [imranbarbhuiya/pagination.djs#44]
Hello, when using this package my bot no longer launches because of the class `MessageEmbed` no longer being in discord.js v14.

```
 Class extends value undefined is not a constructor or null
```

**Comment by hocsinhgioitoan** [comment]
see in here: 
 https://github.com/imranbarbhuiya/pagination.djs/pull/23

**Comment by imranbarbhuiya** [comment]
I'll release stable v14 compatible release today

**Comment by imranbarbhuiya** [comment]
v4.0.0 is released with support for v14. Check https://github.com/imranbarbhuiya/pagination.djs/releases/tag/v4.0.0 for changelog
