### ISSUE TITLE
 setEphemeral(true) is not working

### ISSUE THREAD

**Issue by hocsinhgioitoan** [imranbarbhuiya/pagination.djs#45]
![Screen Shot 2022-07-19 at 11 50 07 AM](https://user-images.githubusercontent.com/89916615/179667235-2edcc968-621c-4565-a640-364f4dd53068.png)

![Screen Shot 2022-07-19 at 11 50 28 AM](https://user-images.githubusercontent.com/89916615/179667359-87558765-58ac-4009-9e7e-d5c6b1c08733.png)

here all

**Comment by imranbarbhuiya** [comment]
fixed in `v4.0.1`

**Comment by hocsinhgioitoan** [comment]
> fixed in `v4.0.1`

not working to
![Screen Shot 2022-07-19 at 3 12 14 PM](https://user-images.githubusercontent.com/89916615/179701182-f818c222-791b-4158-bd9a-495ade16805d.png)
o

**Comment by imranbarbhuiya** [comment]
Unknown interaction means you are replying to the interaction after 3s. It might be due to your internet connection or you are fetching something which is taking 3s+ time.

**Comment by hocsinhgioitoan** [comment]
![Screen Shot 2022-07-19 at 4 21 21 PM](https://user-images.githubusercontent.com/89916615/179715857-8fc20893-5a3e-48e9-9167-24b0084491f7.png)
![Screen Shot 2022-07-19 at 4 21 51 PM](https://user-images.githubusercontent.com/89916615/179715924-920abda1-3b44-41a6-b77e-c2d020048315.png)

idk

**Comment by imranbarbhuiya** [comment]
`editReply` can't make the response ephemeral. You need to pass `{ephemeral: true}` in `deferReply`.

```ts
await interaction.deferReply({ephemeral: true})
```
adding ephemeral only works in `reply` and `deferReply`.
