### ISSUE TITLE
Interaction

### ISSUE THREAD

**Issue by GillHoang** [imranbarbhuiya/pagination.djs#68]
![image](https://user-images.githubusercontent.com/89916615/193412774-07284238-d3de-4b0b-a396-3621b9b3ff08.png)
![image](https://user-images.githubusercontent.com/89916615/193412778-412cca08-d83c-4109-8285-c6978943a655.png)
![image](https://user-images.githubusercontent.com/89916615/193412786-080afd79-f227-4de1-9381-d1a7cf3aa67b.png)

i really don't know why

**Comment by imranbarbhuiya** [comment]
Can you run `yarn why discord.js` or `npm ls discord.js`?

**Comment by imranbarbhuiya** [comment]
I can't reproduce the issue. What version of `pagibation.djs` are u using? also can you please send an ss of 
```ts
console.log(interaction)
```
just before passing to `new Pagination`

**Comment by imranbarbhuiya** [comment]
Can you try uninstalling and installing `pagination.djs` (if that doesn't work, try uninstalling both discord.js and pagination.djs and install again)
